run:
  timeout: 5m
  go: "1.25"

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    rules:
      main:
        deny:
          # Deny dangerous or deprecated packages
          - pkg: "unsafe"
            desc: "unsafe package should be avoided"
        allow:
          # Standard library
          - $gostd
          # Project internal packages
          - github.com/user/docker-image-reporter
          # External dependencies
          - github.com/spf13/cobra
          - github.com/Masterminds/semver/v3
          - gopkg.in/yaml.v3
          - golang.org/x/time/rate
  misspell:
    ignoreWords:
      - comando
      - clientes
      - patrones
      - Patrones
      - componentes
      - directorios
      - presentes
      - originales
      - versiones
      - reportes
      - operacional

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - whitespace
    - bodyclose
    - rowserrcheck
    - exhaustive
    - dogsled
    - nakedret
    - unparam
    - unconvert
    - predeclared

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd